name:                discord
version:             0.1.0.0
github:              "CimimUxMaio/discord"
license:             BSD3
author:              "CimimUxMaio"
maintainer:          "juanbiabdon@gmail.com"
copyright:           "2021 CimimUxMaio"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/discord#readme>


default-extensions:
- OverloadedStrings
- DeriveGeneric
- DeriveAnyClass

dependencies:
- base >= 4.7 && < 5
- transformers
- mtl
- text

library:
  source-dirs: src

tests:
  discord-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord
